---
- name: Deploy web servers
  hosts: webservers
  become: yes

  tasks:
    - name: Update yum cache
      yum:
        name: '*'
        state: latest

    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Configure Apache to listen on port 8080
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        line: 'Listen 8080'
        create: yes
        state: present

    - name: Start and enable Apache service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create index.html with a custom message
      template:
        src: index.html.j2
        dest: /var/www/html/index.html

    - name: Ensure httpd is listening on port 8080
      command: netstat -tuln | grep :8080
      register: netstat_output
      changed_when: false

    - name: Reload Apache configuration
      service:
        name: httpd
        state: reloaded
      when: netstat_output.stdout != ""
